### ISSUE TITLE
Exceptions thrown at start

### ISSUE THREAD

**Issue by jule64** [timolson/cointrader#126]
Hi guys,  

Adding to Tikascar's comments (#124)  I am also unable to start cointrader, I tried out a few revisions and the last revision that seem to work is **6052e33 Douggie on 04/03/2015 at 12:59** 

The revision after that one throws errors (see log extracts below).  I tried other more recent revisions and get other types of errors. Any idea?

Here are the short log extracts sorted by revisions timeline (the bottom ones are the last ones that work for me).  Note I dropped the database and ran the maven build before each tests to simulate starting the app for the first time

 
*****  462eeaa Douggie on 18/07/2015 at 21:53 

ct> markets
markets
2015-08-09 18:07:56 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for MarketsCommand.epl on classpath. Please ensure MarketsCommand.epl is in the resources directory.
2015-08-09 18:07:56 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for CommandBase.epl on classpath. Please ensure CommandBase.epl is in the resources directory.

*****  110b31e Douggie on 20/06/2015 at 10:27

2015-08-09 18:13:58 [main] ERROR org.cryptocoinpartners.bin.Main - Uncaught error while running ConsoleRunMode
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.Error: Property xchange.okcoin.class is not set.  Please edit cointrader-default.properties to specify the correct XChange adapter class.
  at org.cryptocoinpartners.module.xchange.XchangeData.<init>(XchangeData.java:55)
  at org.cryptocoinpartners.module.xchange.XchangeData.class(XchangeData.java:52)
  while locating org.cryptocoinpartners.module.xchange.XchangeData

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1009) ~[guice-4.0-beta4.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1035) ~[guice-4.0-beta4.jar:na]
	at org.cryptocoinpartners.util.Injector.getInstance(Injector.java:30) ~[classes/:na]
	at org.cryptocoinpartners.module.Context.attach(Context.java:152) ~[classes/:na]
	at org.cryptocoinpartners.module.Context.attach(Context.java:145) ~[classes/:na]
	at org.cryptocoinpartners.module.Context.attach(Context.java:116) ~[classes/:na]
	at org.cryptocoinpartners.bin.ConsoleRunMode.init(ConsoleRunMode.java:117) ~[classes/:na]
	at org.cryptocoinpartners.bin.ConsoleRunMode.run(ConsoleRunMode.java:53) ~[classes/:na]
	at org.cryptocoinpartners.bin.Main.main(Main.java:106) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]

******* df42b36 Douggie on 16/05/2015 at 14:19 

2015-08-09 18:19:16 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: null
2015-08-09 18:19:16 [main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - An SQLException was provoked by the following failure: com.mchange.v2.resourcepool.NoGoodResourcesException: After checking so many resources we blew the stack, no resources tested acceptable for checkout. See logger com.mchange.v2.resourcepool.BasicResourcePool output at FINER/DEBUG for information on individual failures.
Exception in thread "main" java.lang.Error: Could not initialize db
	at org.cryptocoinpartners.util.PersistUtil.init(PersistUtil.java:384)
	at org.cryptocoinpartners.util.PersistUtil.init(PersistUtil.java:319)
	at org.cryptocoinpartners.bin.Main.main(Main.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ExceptionInInitializerError
	at org.cryptocoinpartners.util.PersistUtil.ensureSingletonsExist(PersistUtil.java:390)
	at org.cryptocoinpartners.util.PersistUtil.init(PersistUtil.java:377)
	... 7 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Could not open connection
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:524)
	at org.cryptocoinpartners.util.PersistUtil.queryOne(PersistUtil.java:232)
	at org.cryptocoinpartners.schema.Currency.forSymbol(Currency.java:23)
	at org.cryptocoinpartners.schema.Currency.forSymbolOrCreate(Currency.java:41)
	at org.cryptocoinpartners.schema.Currencies.fiat(Currencies.java:196)
	at org.cryptocoinpartners.schema.Currencies.<clinit>(Currencies.java:5)
	... 9 more

********  fe7e4ab Douggie on 20/03/2015 at 21:52 

** this one blocks on the last line:

2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DecimalAmount org.cryptocoinpartners.schema.GeneralOrder.getLimitPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DecimalAmount org.cryptocoinpartners.schema.GeneralOrder.getStopPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DecimalAmount org.cryptocoinpartners.schema.GeneralOrder.getTargetPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DecimalAmount org.cryptocoinpartners.schema.GeneralOrder.getTrailingStopPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DecimalAmount org.cryptocoinpartners.schema.GeneralOrder.getVolume()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DiscreteAmount org.cryptocoinpartners.schema.SpecificOrder.getLimitPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DiscreteAmount org.cryptocoinpartners.schema.SpecificOrder.getStopPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DiscreteAmount org.cryptocoinpartners.schema.SpecificOrder.getTargetPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DiscreteAmount org.cryptocoinpartners.schema.SpecificOrder.getTrailingStopPrice()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DiscreteAmount org.cryptocoinpartners.schema.SpecificOrder.getUnfilledVolume()
2015-08-09 18:26:14 [pool-1-thread-1] WARN  c.e.esper.event.bean.PropertyHelper - .getAccessors Unable to obtain CGLib fast method implementation, msg=Cannot find method public org.cryptocoinpartners.schema.DiscreteAmount org.cryptocoinpartners.schema.SpecificOrder.getVolume()
hash=-2060760508 size=0
hash=1606605745 size=0
hash=1556211970 size=0
hash=-436645643 size=0
hash=-1568199381 size=0
hash=885131792 size=0
2015-08-09 18:26:22 [main] INFO  o.h.e.j.c.i.DriverManagerConnectionProviderImpl - HHH000030: Cleaning up connection pool [jdbc:mysql://localhost:3306/cointrader]

**********  4b1c90f Douggie on 07/03/2015 at 11:39 

2015-08-09 18:29:41 [main] DEBUG org.cryptocoinpartners.persist - Listing: 95e258bc-e20f-4e98-8e30-594c0b3f91e5 saved to database
2015-08-09 18:29:41 [main] DEBUG org.cryptocoinpartners.persist - Market: dd25c21c-f6db-4de9-a39d-42597c9aa283 saved to database
2015-08-09 18:29:41 [main] DEBUG org.cryptocoinpartners.persist - Market: 35f487b1-18fb-4e35-97fe-ff04d0550720 saved to database
2015-08-09 18:29:41 [main] DEBUG org.cryptocoinpartners.persist - Market: 334afa93-13f4-444b-92ec-d8ea70929c2c saved to database
2015-08-09 18:29:41 [main] DEBUG org.cryptocoinpartners.persist - Market: 05900bd3-2651-45d8-aa0e-b14c3fc1f0a2 saved to database
Exception in thread "pool-4-thread-1" java.lang.NullPointerException
	at com.xeiam.xchange.bitfinex.v1.service.polling.BitfinexMarketDataService.getTrades(BitfinexMarketDataService.java:130)
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesRunnable.getTrades(XchangeData.java:186)
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesRunnable.run(XchangeData.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-4-thread-2" com.xeiam.xchange.exceptions.ExchangeException: Argument 0 must be an Integer!
	at com.xeiam.xchange.bitfinex.v1.service.polling.BitfinexMarketDataService.getOrderBook(BitfinexMarketDataService.java:62)
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesRunnable.getBook(XchangeData.java:220)
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesRunnable.run(XchangeData.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-4-thread-3" java.lang.NullPointerException
	at com.xeiam.xchange.bitfinex.v1.service.polling.BitfinexMarketDataService.getTrades(BitfinexMarketDataService.java:130)
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesRunnable.getTrades(XchangeData.java:186)
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesRunnable.run(XchangeData.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**********  6052e33 Douggie on 04/03/2015 at 12:59 
**  ok

***********  cd9a022 Douggie on 20/02/2015 at 07:06 
ok

****** 47b1db6 tim on 12/02/2015 at 05:17 
ok:
ct> markets
markets
2015-08-09 18:56:38 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for MarketsCommand.epl on classpath. Please ensure MarketsCommand.epl is in the resources directory.
2015-08-09 18:56:38 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for CommandBase.epl on classpath. Please ensure CommandBase.epl is in the resources directory.
    • BITFINEX:BTC.USD
    • BITFINEX:LTC.BTC
    • BITFINEX:LTC.USD
    • BITSTAMP:BTC.USD
    • BTER:BTC.USD
    • BTER:LTC.BTC
    • BTER:LTC.USD

**Comment by douggie** [comment]
Hi Jullian,

I have negleted to console, just checked in a bunch of fixes and it should
now be working. However save-data should have been working as well as the
backtest.

Still can't figure out Tikascar's issues. I am trying to replicate.

let me know how you get on with the latest code and the console.

**Comment by douggie** [comment]
you might need to drop the following tables in your db:



delete from general_order;
delete from order_children;
delete from `transaction`;
delete from fill;
delete from position;
delete from `specific_order`;
delete from `portfolio`;
delete from `order_update`;

**Comment by nimrood** [comment]
I also receive exceptions on start that are similar to @Tikaszar's issue #124.  The schema is being created/updated but tables appear to be empty. It looks like `PersistUtil.ensureSingletonsExist()` fails because there are no rows in the tables -- "no singletons exist" in the db.

**Comment by douggie** [comment]
Hummm, trying to replicate on linux.

**Comment by jule64** [comment]
It looks like the issue is that PersistUtil.insert() does not actually persist to the db, only adds to a queue.

**Comment by douggie** [comment]
HI Julien, that is correct, there are two threads that are started to do
the persistance, InsertRunnable and MergeRunnable, pool-4-thread-1 and
pool4-thread-2.

I wondered if these are dying. Could you porivde a jstack pid so I can see
the stack trace.

**Comment by jule64** [comment]
Nice, I'll have a look later today and update back. Thanks Douggie

**Comment by jule64** [comment]
The problem is that the threads are after ensureSingletonsExist(); so they don't even get a chance to start..  Moving them before the try block fixes the "Could not initialize db" exception.
The next issue is that the **market** table is empty.. can't figure out where the static is supposed to come from

**Comment by douggie** [comment]
Hi Julien,

good spot!

Fix checked in. For the markets, they are created from you
cointrader.properties file.

something along the lines of the following.

You might need to run save-data for the markets to be created as per your
properties file.

**Comment by jule64** [comment]
Thanks Douggie, got markets added, all good now :)

**Comment by douggie** [comment]
good news, thanks for finding the issue.

**Comment by douggie** [comment]
the idea is that we did not want peristance to slow down performance, hence
the comsumer/producer. There is a still a few issues with the persistance
context in that it does not always have the entities when they are
persisted by another entity manager. I have not had time to debug it, but
generally it all get's stored eventally but you might see some trying to
persist detached entity.

**Comment by jule64** [comment]
Thanks for the explanation.  have you looked at hibernate or a caching layer to handle these asynchronous read/writes?

**Comment by douggie** [comment]
there is a level2 ehcahce implemented, 9/10 it works fine, but some of the
entities become detached, I have not had a chance to debug it.
