### ISSUE TITLE
Exception during ReportDataRunMode

### ISSUE THREAD

**Issue by buffxz** [timolson/cointrader#132]
I am seeing this exp:

````
2016-02-24 23:44:57 [main] ERROR org.cryptocoinpartners.bin.Main - Uncaught error while running ReportDataRunMode
java.lang.NullPointerException: null
	at org.cryptocoinpartners.util.PersistUtil.createEntityManager(PersistUtil.java:699) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.util.PersistUtil.queryEach(PersistUtil.java:507) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.util.PersistUtil.queryEach(PersistUtil.java:496) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.report.JpaReport.runReport(JpaReport.java:53) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.bin.ReportRunMode.run(ReportRunMode.java:14) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.cryptocoinpartners.bin.Main.main(Main.java:129) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
````

**Comment by douggie** [comment]
hi Xu,

Most likey the entity manager is not getting injected correctly, I will
cehck this
