### ISSUE TITLE
Cannot exit console

### ISSUE THREAD

**Issue by petervilleroy** [timolson/cointrader#137]
I'm using Windows7 / Maven 3.3.9 / MySQL 5.7.13

```
ct> exit
2016-07-05 09:29:23 [main] DEBUG c.e.e.c.deploy.EPDeploymentAdminImpl - Reading
resource 'ExitCommand.epl'
2016-07-05 09:29:23 [main] DEBUG o.cryptocoinpartners.module.Context - no module
 file found for ExitCommand.epl on classpath. Please ensure ExitCommand.epl is i
n the resources directory.
2016-07-05 09:29:23 [main] DEBUG c.e.e.c.deploy.EPDeploymentAdminImpl - Reading
resource 'CommandBase.epl'
2016-07-05 09:29:23 [main] DEBUG o.cryptocoinpartners.module.Context - no module
 file found for CommandBase.epl on classpath. Please ensure CommandBase.epl is i
n the resources directory.
2016-07-05 09:29:23 [main] INFO  org.cryptocoinpartners.persist - initializing p
ersistence
2016-07-05 09:29:23 [main] WARN  org.cryptocoinpartners.runMode - Could not run
command exit
java.lang.NullPointerException: null
        at org.cryptocoinpartners.util.PersistUtil.createEntityManager(PersistUt
il.java:699) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.cryptocoinpartners.util.PersistUtil.shutdown(PersistUtil.java:724
) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.cryptocoinpartners.command.ExitCommand.run(ExitCommand.java:27) ~
[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.cryptocoinpartners.bin.ConsoleRunMode.run(ConsoleRunMode.java:94)
 ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.cryptocoinpartners.bin.Main.main(Main.java:129) [cointrader-0.3.0
-SNAPSHOT-jar-with-dependencies.jar:na]
Internal error: see cointrader.log

ct>

```

And the entry in ciontrader.log:

```
2016-07-05 09:29:17 [main] WARN  org.cryptocoinpartners.runMode - Could not run command exit
java.lang.NullPointerException: null
    at org.cryptocoinpartners.util.PersistUtil.createEntityManager(PersistUtil.java:699) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.util.PersistUtil.shutdown(PersistUtil.java:724) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.command.ExitCommand.run(ExitCommand.java:27) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.bin.ConsoleRunMode.run(ConsoleRunMode.java:94) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.bin.Main.main(Main.java:129) [cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
2016-07-05 09:29:23 [main] DEBUG c.e.e.c.deploy.EPDeploymentAdminImpl - Reading resource 'ExitCommand.epl'
2016-07-05 09:29:23 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for ExitCommand.epl on classpath. Please ensure ExitCommand.epl is in the resources directory.
2016-07-05 09:29:23 [main] DEBUG c.e.e.c.deploy.EPDeploymentAdminImpl - Reading resource 'CommandBase.epl'
2016-07-05 09:29:23 [main] DEBUG o.cryptocoinpartners.module.Context - no module file found for CommandBase.epl on classpath. Please ensure CommandBase.epl is in the resources directory.
2016-07-05 09:29:23 [main] INFO  org.cryptocoinpartners.persist - initializing persistence
2016-07-05 09:29:23 [main] WARN  org.cryptocoinpartners.runMode - Could not run command exit
java.lang.NullPointerException: null
    at org.cryptocoinpartners.util.PersistUtil.createEntityManager(PersistUtil.java:699) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.util.PersistUtil.shutdown(PersistUtil.java:724) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.command.ExitCommand.run(ExitCommand.java:27) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.bin.ConsoleRunMode.run(ConsoleRunMode.java:94) ~[cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.cryptocoinpartners.bin.Main.main(Main.java:129) [cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar:na]

```

Note: virtually all the obscure errors I get using cointrade refer to missing *.epl files in the resources directory. Currently, only one *.epl file exists there: BasicPortfolioService.epl

**Comment by douggie** [comment]
hi, will take a look at the exit. the epl are just notifications, i will
remove the log entries as they confuse everyone!
