### ISSUE TITLE
NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by IanWorthington** [timolson/cointrader#149]
Any suggestions of what might be causing this?  Have just rebuilt with the latest updates.

C:\Users\Ian\git2\cointrader\target>java -jar cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar console
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/Ian/git2/cointrader/target/cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1                             WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                           WARNING: All illegal access operations will be denied in a future release
2018-03-31 18:58:58 [main] INFO  o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [
        name: org.cryptocoinpartners.schema
        ...]
2018-03-31 18:58:58 [main] INFO  org.hibernate.Version - HHH000412: Hibernate Core {[WORKING]}
2018-03-31 18:58:58 [main] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
  at org.cryptocoinpartners.module.ApplicationInitializer.<init>(ApplicationInitializer.java:68)
  at org.cryptocoinpartners.module.ApplicationInitializer.class(ApplicationInitializer.java:31)
  while locating org.cryptocoinpartners.module.ApplicationInitializer

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at org.cryptocoinpartners.util.Injector.getInstance(Injector.java:35)
        at org.cryptocoinpartners.bin.Main.main(Main.java:71)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43)
        at org.hibernate.boot.MetadataSources.<init>(MetadataSources.java:87)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:208)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:170)
        at org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:76)
        at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilder(HibernatePersistenceProvider.java:181)
        at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:129)
        at org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:71)
        at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:52)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at com.google.inject.persist.jpa.JpaPersistService.start(JpaPersistService.java:108)
        at org.cryptocoinpartners.module.ApplicationInitializer.<init>(ApplicationInitializer.java:69)
        at org.cryptocoinpartners.module.ApplicationInitializer$$FastClassByGuice$$ca919e6d.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 28 more

**Comment by douggie** [comment]
does your src/main/resources/META-INF/persistence.xml exist? do all your tables exist in you DB and the login details correct?

I have not see this before but the errors when the DB connections are not working can be cryptic.

**Comment by IanWorthington** [comment]
As it's running the jar-with-dependencies, I think you probably mean cointrader-0.3.0-SNAPSHOT-jar-with-dependencies.jar\META-INF\, yes?  There's a persistence.xml built into that.  I did the db setup and it runs fine under eclipse so I assume the db is ok.

**Comment by IanWorthington** [comment]
Could it be something to do with the change of hibernate version?

**Comment by douggie** [comment]
so may be the jvm? may be something needs to be set on the command Line.
The following oralce JVM works for me ok.

**Comment by douggie** [comment]
java version "1.8.0_161"

**Comment by douggie** [comment]
possible related https://github.com/gradle/gradle/issues/3118.

**Comment by douggie** [comment]
could it be the your eclipse and local command line are suing different
JDK's?

**Comment by IanWorthington** [comment]
Buggeration.  I had Java 9 installed.  Eclipse was using 1.8.  Looks like 9 breaks a lot of stuff.  

My bad.
