### ISSUE TITLE
exit fails

### ISSUE THREAD

**Issue by IanWorthington** [timolson/cointrader#151]
Looks like this is #137 again?

ct> exit
2018-03-31 21:38:18 [main] INFO  org.cryptocoinpartners.persist - initializing persistence
2018-03-31 21:38:18 [main] WARN  org.cryptocoinpartners.runMode - Could not run command exit
java.lang.NullPointerException: null
	at org.cryptocoinpartners.util.PersistUtil.createEntityManager(PersistUtil.java:698) ~[classes/:na]
	at org.cryptocoinpartners.util.PersistUtil.shutdown(PersistUtil.java:723) ~[classes/:na]
	at org.cryptocoinpartners.command.ExitCommand.call(ExitCommand.java:27) ~[classes/:na]
	at org.cryptocoinpartners.bin.ConsoleRunMode.run(ConsoleRunMode.java:92) ~[classes/:na]
	at org.cryptocoinpartners.bin.Main.main(Main.java:133) [classes/:na]
Internal error: see cointrader.log

**Comment by IanWorthington** [comment]
Don't think exit is a biggie, but the commands as whole are the first thing newbies like me will try so it's important that they more-or-less work as installation verification.

**Comment by douggie** [comment]
totally agree.

**Comment by IanWorthington** [comment]
Added a PR to ensure that exit always exits, regardless of anything that happens.
