### ISSUE TITLE
Is last version working?

### ISSUE THREAD

**Issue by EgorKuts** [timolson/cointrader#155]
I've saved this properties:

#database
db.username=root
db.password=mypassword
db.url=jdbc:mysql://localhost:3306/cointrader?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
db.driver=com.mysql.jdbc.Driver
db.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
db.pool.size=20
db.pool.growth=35
db.replay.reader.threads=5
db.book.writer.threads=10
db.trade.writer.threads=5
db.bar.writer.threads=5
fill.processing.threads=2
db.writer.delay=1000
db.idle.test.period=3000
db.max.connection.age=3600
db.test.connection=false
db.persist.retry=4
db.marketdata.writer.threads=5
#exchanges
xchange.poloniex.class=org.knowm.xchange.poloniex.PoloniexExchange
xchange.poloniex.rate.queries=3
xchange.poloniex.rate.period=5000
xchange.poloniex.rate.period=5
xchange.poloniex.listings=BTC.ETH

And when i'm launching cointrader via "./cointrader.sh console", i'm getting this exception(i found it and wrote print stack trace, because without that, it doesn't work dumbly):

2018-06-06 23:22:17 [pool-11-thread-1] INFO  org.cryptocoinpartners.xchangeData - XchangeData:getTrades Unabel to get trade for market POLONIEX:BTC.ETH pair BTC/ETH.  Failure 3 of 10. 
org.knowm.xchange.exceptions.ExchangeException: Invalid currency pair.
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.getPoloniexPublicTrades(PoloniexMarketDataServiceRaw.java:148)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataService.getTrades(PoloniexMarketDataService.java:81)
	at org.cryptocoinpartners.module.xchange.XchangeData.getTrades(XchangeData.java:269)
	at org.cryptocoinpartners.module.xchange.XchangeData$FetchTradesRunnable.run(XchangeData.java:470)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.knowm.xchange.poloniex.PoloniexException: Invalid currency pair. (HTTP status code: 200)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:421)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3030)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
	at com.sun.proxy.$Proxy106.getTrades(Unknown Source)
	at org.knowm.xchange.poloniex.service.PoloniexMarketDataServiceRaw.getPoloniexPublicTrades(PoloniexMarketDataServiceRaw.java:145)
	... 6 more

**Comment by douggie** [comment]
seems like not a vaild pair on polinex or not support by xchange lib.

**Comment by douggie** [comment]
i can take a look if you update logback.xml to vut resu into debug you can
see the api call it should be

https://poloniex.com/public?command=returnTradeHistory&currencyPair=BTC_ETH

**Comment by EgorKuts** [comment]
Problem was solved, Poloniex does not provide that pairs(just my stupid mistake)
